substitutions:
  name: athom-garage-door-9ce706
  friendly_name: Athom Garage Door
packages:
  Athom Technology.Athom Garage Door Opener: github://athom-tech/athom-configs/athom-garage-door.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 71JStmTCAZM8uAHnTtVFHpaNzkSR5m7ySM8kz+iU+eo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
