# do not change nor update!!!!!
# working esphome version is 
# version := "2024.12.0"
substitutions:
  device_name: esp-ultrasonic

esphome:
  name: ${device_name}
  friendly_name: "ESPHOME Ultrasonic Sensor"
  platformio_options: 
    build_flags: "-DI2C_NUM_1=I2C_NUM_0"
  on_boot:
    priority: 100.0
    then:
      - logger.log:
          format: "Hello world"
          level: INFO

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  logs:
    wifi_info: ERROR
    wifi_signal: ERROR
    wifi: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP Address
    ssid:
      name: ${device_name} SSID
    mac_address:
      name: ${device_name} Mac Address


sensor:
  - platform: wifi_signal
    name: ${device_name} rssi
    update_interval: 60s
  - platform: ultrasonic
    trigger_pin: GPIO20
    echo_pin: GPIO18
    name: "Ultrasonic Sensor"
    update_interval: 1s
    accuracy_decimals: 2
    unit_of_measurement: m
    pulse_time: 25us
    timeout: 3m
    filters:
      - sliding_window_moving_average:
          window_size: 10 #creates a moving average of the last 10 values
          send_every: 1 #sends the moving average at every measurement (but only if it passes the delta filter below)) 
          send_first_at: 1 #after startup immediately start sending the result rather than wait for the first 10 measurements
      - delta : 0.05 #only send the result if the level difference with the last sent result is higher than this
      - filter_out: nan

web_server:
  port: 80
