substitutions:
  name: everything-presence-lite-4fa374
  friendly_name: Everything Presence Lite 4fa374
packages:
  EverythingSmartTechnology.Everything Presence Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: UOzwsNGi7oLY8zGIxUyPPxkq8KMoCbhvVEPMYf4ZWos=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.20.147
    gateway: 192.168.20.1
    subnet: 255.255.255.0
