substitutions:
  name: everything-presence-lite-4fa374
  friendly_name: Everything Presence Lite 4fa374
packages:
  EverythingSmartTechnology.Everything Presence Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: UOzwsNGi7oLY8zGIxUyPPxkq8KMoCbhvVEPMYf4ZWos=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  logs:
    sensor: NONE
    binary_sensor: NONE
    component: ERROR
    esp-idf: ERROR
    http_request: ERROR
web_server:
