substitutions:
  preset_1_height: "67"
  preset_1_label: "Sitting"
  preset_1_icon: "\U000F0F48"  # chair-rolling

  preset_2_height: "70"
  preset_2_label: "Bike"
  preset_2_icon: "\U000F109C"  # bicycle

  preset_3_height: "75"
  preset_3_label: "Standing"
  preset_3_icon: "\U000F1239"  # human-male-height

esphome:
  name: m5stack-dial
  friendly_name: M5Stack Dial
  on_boot:
    then:
      - light.turn_on: display_backlight
      - pcf8563.read_time:
      - delay: 1s
      - script.execute: update_preset_selection
      - script.execute: update_preset_labels
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

packages:
  connectivity: !include m5dial/connectivity.yaml
  hardware: !include m5dial/hardware.yaml
  sensors: !include m5dial/sensors.yaml
  desk_control: !include m5dial/desk_control.yaml
  display_ui: !include m5dial/display_ui.yaml
