substitutions:
  name: "tx-ultimate"
  friendly_name: "TX Ultimate łazienka"
  device_format: EU
  gang_count: 1
  expose_relays_leds_to_ha: false
  relay_1_mode: light


packages:
  remote_package:
    url: https://github.com/edwardtfn/TX-Ultimate-Easy
    ref: main  # Or you can specify a version, like `ref: v2024.12.6` or `ref: latest`
    refresh: 5min
    files:
      - ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml      # Core (essential) packages
      - ESPHome/TX-Ultimate-Easy-ESPHome_hw_relays.yaml     # Relay control
      - ESPHome/TX-Ultimate-Easy-ESPHome_media_player.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false

api:
  encryption:
    key: "kzSdAMyTlAI1fR0s0PYZipyt124udJbXqkBJMMl1gA0="

ota:
  password: "09eb2623ca2ca44e8637536eac0dfaf4"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name} AP
    password: "top_secret"

script:
  - id: !extend touch_on_multi_touch_release
    then:
      - light.toggle: light_output_1
  - id: !extend touch_swipe_${ID_SWIPE_LEFT_OR_UP_TEXT}
    then:
      - light.toggle: light_output_1
  - id: !extend touch_swipe_${ID_SWIPE_RIGHT_OR_DOWN_TEXT}
    then:
      - light.toggle: light_output_1

